INFO     root:HmsManager.py:28 2023-01-20 16:50:06: login HMS, ip: 172.16.2.220,username: root
INFO     root:HmsManager.py:30 2023-01-20 16:50:07: login HMS success!
INFO     root:HmsManager.py:46 2023-01-20 16:50:07: query gnb info
INFO     root:HmsManager.py:48 2023-01-20 16:50:07: enbId/enbName:4/Automatic-18
INFO     root:CpeManager.py:28 2023-01-20 16:50:07: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
INFO     root:CellManager.py:58 2023-01-20 16:50:07: confirm if cell status is same as expect status,expect status:available
INFO     root:CellManager.py:26 2023-01-20 16:50:07: query cell status
INFO     root:CellManager.py:36 2023-01-20 16:50:07: cell status:available
INFO     root:CellManager.py:65 2023-01-20 16:50:07: cell status:available, expect status:available
INFO     root:CpeManager.py:429 2023-01-20 16:50:07: start ue log trace
INFO     root:qutsModel.py:88 printing the chip name of the first device with DIAG_PROT:
INFO     root:qutsModel.py:92 SDX55
INFO     root:qutsModel.py:110 QXDM automation interface successfully launched
INFO     root:qutsModel.py:114 connecting to device with devicehandle=1970324836974592, len=16; protoHandle=1970329131941888, len=16
INFO     root:qutsModel.py:120 QXDM successfully connects to device with deviceHandle=1970324836974592, protHandle=1970329131941888
INFO     root:CpeManager.py:46 2023-01-20 16:50:16: exec attach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=1
INFO     root:cpeModel.py:82 mattch result is:['root@OpenWrt:~# at_cmd_task', 'OK']
INFO     root:CpeManager.py:120 2023-01-20 16:50:20: confirm if pdu setup success
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:126 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-01-20 16:50:25: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is['190.1.2.166', '190.3.2.143']
INFO     root:basic.py:30 2023-01-20 16:50:35: wait for 10s......
INFO     root:CpeManager.py:95 2023-01-20 16:50:45: exec ping command, interface: rmnet_data0
INFO     root:cpeModel.py:144 ping result mattched is:['9.229/11.764/14.504']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['20']
INFO     root:cpeModel.py:172 packet loss:['0%']
INFO     root:CpeManager.py:98 2023-01-20 16:51:10: Cpe[192.168.1.1_rmnet_data0] ping result[max/avg/min/transmitted/received/loss rate] = 14.504/11.764/9.229/20/20/0%
INFO     root:CpeManager.py:439 2023-01-20 16:51:10: stop ue log trace
INFO     root:qutsModel.py:136 hdf is saved to ['D:\\autotestPro\\AutoTestMain\\qxdmLog\\71bb7cf1-3ece-4375-9d92-44f77062d7e3_50191_Diag_2500-ffff192_168_1_1_0.hdf']
INFO     root:CpeManager.py:626 2023-01-20 16:51:10: support DMRS mapping type A
INFO     root:qCatModel.py:46 Open Ue Log Success
INFO     root:CpeManager.py:628 2023-01-20 16:51:13: check result is:{'format1': False, 'format3': True, 'dmrs dl type': True, 'dmrs ul type': True, 'dmrs dl type1': True, 'dmrs ul type1': True}
INFO     root:CpeManager.py:62 2023-01-20 16:51:13: exec detach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=0
INFO     root:cpeModel.py:82 mattch result is:['', 'OK']
INFO     root:test_phy.py:442 2023-01-20 16:51:17: move the log file to backup folder