INFO     root:test_version.py:213 2023-02-10 15:37:59run the test <1> times
INFO     root:HmsManager.py:28 2023-02-10 15:37:59: login HMS, ip: 172.16.2.220,username: root
INFO     root:HmsManager.py:30 2023-02-10 15:37:59: login HMS success!
INFO     root:HmsManager.py:46 2023-02-10 15:37:59: query gnb info
INFO     root:HmsManager.py:48 2023-02-10 15:37:59: enbId/enbName:14/Automatic-18
INFO     root:gnbManager.py:24 2023-02-10 15:37:59: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B07101DC0>
INFO     root:VersionManager.py:199 2023-02-10 15:37:59: query gnb version info from device
INFO     root:VersionManager.py:233 2023-02-10 15:37:59: query package exist in version manager or not
INFO     root:VersionManager.py:238 2023-02-10 15:37:59: the package has existed in version manager!
INFO     root:gnbManager.py:57 2023-02-10 15:37:59: open gnb log print switch.
INFO     root:gnbModel.py:91 open log print success.
INFO     root:VersionManager.py:25 2023-02-10 15:38:00: exec download task, version: BS5514_V1.20.00
INFO     root:VersionManager.py:41 2023-02-10 15:38:03: download exec success!
INFO     root:VersionManager.py:60 2023-02-10 15:38:03: query status of download task!
INFO     root:basic.py:30 2023-02-10 15:38:03: wait for 30s......
INFO     root:VersionManager.py:69 2023-02-10 15:38:33: download task exec success!
INFO     root:VersionManager.py:214 2023-02-10 15:38:33: query gnb version info from device
INFO     root:VersionManager.py:89 2023-02-10 15:38:34: exec active task!
INFO     root:VersionManager.py:102 2023-02-10 15:38:38: active exec success!
INFO     root:VersionManager.py:116 2023-02-10 15:38:38: query status of active task
INFO     root:basic.py:30 2023-02-10 15:38:38: wait for 30s......
INFO     root:basic.py:30 2023-02-10 15:39:08: wait for 30s......
INFO     root:basic.py:30 2023-02-10 15:39:38: wait for 30s......
INFO     root:basic.py:30 2023-02-10 15:40:08: wait for 30s......
INFO     root:basic.py:30 2023-02-10 15:40:38: wait for 30s......
INFO     root:VersionManager.py:124 2023-02-10 15:41:08: active task exec success!
INFO     root:test_version.py:287 2023-02-10 15:41:08: active success, gnb will auto reboot, wait for 3min......
INFO     root:basic.py:30 2023-02-10 15:41:08: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 15:44:08: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:08: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:13: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:18: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:23: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:28: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:33: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:38: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:43: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:48: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:53: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:44:58: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:45:03: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:45:08: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:45:13: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:45:18: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:45:23: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:45:28: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:45:34: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:45:39: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:45:44: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 15:45:49: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 15:45:49: gnb is online
INFO     root:VersionManager.py:214 2023-02-10 15:45:49: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 15:45:51: query gnb version info from device
INFO     root:test_version.py:385 2023-02-10 15:45:51:confirm if the upgrade version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 15:45:51: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 15:45:53: query gnb version info from device
INFO     root:test_version.py:409 2023-02-10 15:45:53: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/cd4d73baa4f801d9d95c3d7a306a0086da946e7f/D-PHY-c084df/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 15:45:53: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B072A05E0>
INFO     root:gnbManager.py:35 2023-02-10 15:46:08: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 4bd9525882f473e5fadcf1f65639f9bc
INFO     root:gnbManager.py:46 2023-02-10 15:46:10: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-8f885f021 nrsys_ver=v21.04.01-306-g7f42f7235-8be957c, nrsysRes: v21.04.01-306-g7f42f7235-8be957c
INFO     root:test_version.py:421 2023-02-10 15:46:11: version detail check success, version info[gps/nrsys]: 4bd9525882f473e5fadcf1f65639f9bc/v21.04.01-306-g7f42f7235-8be957c
INFO     root:CellManager.py:58 2023-02-10 15:46:11: confirm if cell status is same as expect status,expect status:available
INFO     root:CellManager.py:26 2023-02-10 15:46:11: query cell status
WARNING  root:CellManager.py:40 2023-02-10 15:46:12: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 15:46:12: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 15:46:17: query cell status
WARNING  root:CellManager.py:40 2023-02-10 15:46:18: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 15:46:18: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 15:46:23: query cell status
WARNING  root:CellManager.py:40 2023-02-10 15:46:24: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 15:46:24: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 15:46:29: query cell status
WARNING  root:CellManager.py:40 2023-02-10 15:46:30: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 15:46:30: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 15:46:35: query cell status
WARNING  root:CellManager.py:40 2023-02-10 15:46:36: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 15:46:36: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 15:46:41: query cell status
WARNING  root:CellManager.py:40 2023-02-10 15:46:42: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 15:46:42: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 15:46:47: query cell status
WARNING  root:CellManager.py:40 2023-02-10 15:46:48: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 15:46:48: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 15:46:53: query cell status
WARNING  root:CellManager.py:40 2023-02-10 15:46:54: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 15:46:54: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 15:46:59: query cell status
INFO     root:CellManager.py:36 2023-02-10 15:46:59: cell status:available
INFO     root:CellManager.py:65 2023-02-10 15:46:59: cell status:available, expect status:available
INFO     root:basic.py:30 2023-02-10 15:46:59: wait for 60s......
INFO     root:test_version.py:137 2023-02-10 15:47:59: exec cpe business test
INFO     root:CpeManager.py:28 2023-02-10 15:47:59: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
INFO     root:CpeManager.py:48 2023-02-10 15:48:00: exec attach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=1
INFO     root:cpeModel.py:82 mattch result is:['root@OpenWrt:~# at_cmd_task', 'OK']
INFO     root:CpeManager.py:122 2023-02-10 15:48:04: confirm if pdu setup success
INFO     root:cpeModel.py:129 ip info mattch result is['190.1.70.69', '190.3.75.251']
INFO     root:test_version.py:144 2023-02-10 15:48:09: cpe attach sussess
INFO     root:CpeManager.py:97 2023-02-10 15:48:09: exec ping command, interface: rmnet_data0
INFO     root:cpeModel.py:144 ping result mattched is:['10.606/12.414/14.364']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['15']
INFO     root:cpeModel.py:172 packet loss:['25%']
INFO     root:CpeManager.py:100 2023-02-10 15:48:34: Cpe[192.168.1.1_rmnet_data0] ping result[max/avg/min/transmitted/received/loss rate] = 14.364/12.414/10.606/20/15/25%
INFO     root:CpeManager.py:97 2023-02-10 15:48:34: exec ping command, interface: ath0
INFO     root:cpeModel.py:144 ping result mattched is:['4.694/7.397/32.690']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['17']
INFO     root:cpeModel.py:172 packet loss:['15%']
INFO     root:CpeManager.py:100 2023-02-10 15:48:59: Cpe[192.168.1.1_ath0] ping result[max/avg/min/transmitted/received/loss rate] = 32.690/7.397/4.694/20/17/15%
INFO     root:test_version.py:154 2023-02-10 15:48:59: start cell flow test.
INFO     root:pndManager.py:26 2023-02-10 15:48:59: login pdn server: 172.16.2.202
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_7.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:pdnModel.py:33 login pdn server success!
INFO     root:test_version.py:169 2023-02-10 15:48:59: ue traffic test
INFO     root:CpeManager.py:334 2023-02-10 15:48:59: exec DL NR TCP flow test
INFO     root:CpeManager.py:336 2023-02-10 15:48:59: add port rule
INFO     root:CpeManager.py:342 2023-02-10 15:49:10: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 15:49:10: start pdn server port listening, port: 5579
INFO     root:CpeManager.py:347 2023-02-10 15:49:11: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5579 -P 3 -R
INFO     root:basic.py:30 2023-02-10 15:49:16: wait for 15s......
INFO     root:CpeManager.py:351 2023-02-10 15:49:31: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:pndManager.py:60 2023-02-10 15:50:22: stop pdn server port listening, port: 5579
INFO     root:CpeManager.py:355 2023-02-10 15:50:24: DL TCP NR test result:
[2023-02-10 15:49:46]:0
[2023-02-10 15:49:47]:0
[2023-02-10 15:49:48]:59.18 M
[2023-02-10 15:49:49]:59.31 M
[2023-02-10 15:49:50]:59.18 M
[2023-02-10 15:49:51]:118.38 M
[2023-02-10 15:49:52]:0
[2023-02-10 15:49:53]:59.31 M
[2023-02-10 15:49:54]:59.18 M
[2023-02-10 15:49:55]:59.31 M
[2023-02-10 15:49:56]:59.18 M
[2023-02-10 15:49:57]:59.31 M
[2023-02-10 15:49:58]:59.18 M
[2023-02-10 15:49:59]:59.31 M
[2023-02-10 15:50:00]:59.18 M
[2023-02-10 15:50:01]:59.31 M
[2023-02-10 15:50:02]:59.18 M
[2023-02-10 15:50:03]:59.31 M
[2023-02-10 15:50:04]:59.18 M
[2023-02-10 15:50:05]:59.31 M
[2023-02-10 15:50:06]:59.18 M
[2023-02-10 15:50:07]:59.31 M
[2023-02-10 15:50:08]:59.18 M
[2023-02-10 15:50:09]:59.31 M
[2023-02-10 15:50:10]:59.18 M
[2023-02-10 15:50:11]:59.31 M
[2023-02-10 15:50:12]:59.18 M
[2023-02-10 15:50:13]:59.31 M
[2023-02-10 15:50:14]:59.18 M
[2023-02-10 15:50:15]:59.31 M
[2023-02-10 15:50:16]:59.18 M

INFO     root:basic.py:30 2023-02-10 15:50:24: wait for 20s......
INFO     root:CpeManager.py:298 2023-02-10 15:50:44: exec DL WIFI TCP flow test
INFO     root:CpeManager.py:300 2023-02-10 15:50:44: add port rule
INFO     root:CpeManager.py:306 2023-02-10 15:50:55: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 15:50:55: start pdn server port listening, port: 5599
INFO     root:CpeManager.py:311 2023-02-10 15:50:56: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5599 -P 3 -R
INFO     root:CpeManager.py:315 2023-02-10 15:50:59: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:basic.py:30 2023-02-10 15:51:45: wait for 20s......
INFO     root:pndManager.py:60 2023-02-10 15:52:05: stop pdn server port listening, port: 5599
INFO     root:CpeManager.py:320 2023-02-10 15:52:07: DL TCP Wifi test result:
[2023-02-10 15:51:13]:0
[2023-02-10 15:51:14]:0
[2023-02-10 15:51:15]:98.81 M
[2023-02-10 15:51:16]:98.81 M
[2023-02-10 15:51:17]:98.46 M
[2023-02-10 15:51:18]:98.46 M
[2023-02-10 15:51:19]:98.73 M
[2023-02-10 15:51:20]:98.73 M
[2023-02-10 15:51:21]:99.44 M
[2023-02-10 15:51:22]:99.44 M
[2023-02-10 15:51:23]:99.31 M
[2023-02-10 15:51:24]:99.31 M
[2023-02-10 15:51:25]:99.31 M
[2023-02-10 15:51:26]:99.05 M
[2023-02-10 15:51:27]:99.05 M
[2023-02-10 15:51:28]:99.32 M
[2023-02-10 15:51:29]:99.32 M
[2023-02-10 15:51:30]:99.14 M
[2023-02-10 15:51:31]:99.14 M
[2023-02-10 15:51:32]:98.93 M
[2023-02-10 15:51:33]:98.93 M
[2023-02-10 15:51:34]:98.91 M
[2023-02-10 15:51:35]:98.91 M
[2023-02-10 15:51:36]:98.82 M
[2023-02-10 15:51:37]:98.82 M
[2023-02-10 15:51:38]:99.17 M
[2023-02-10 15:51:39]:99.17 M
[2023-02-10 15:51:40]:99.01 M
[2023-02-10 15:51:41]:99.01 M
[2023-02-10 15:51:42]:98.98 M
[2023-02-10 15:51:43]:98.98 M

INFO     root:CpeManager.py:39 2023-02-10 15:52:07: logout cpe command model
INFO     root:test_version.py:309 2023-02-10 15:52:07: rollback gnb version:BS5514_V1.10.80P1
INFO     root:VersionManager.py:144 2023-02-10 15:52:07: exec rollabck task
INFO     root:VersionManager.py:158 2023-02-10 15:52:10: rollback exec success!
INFO     root:VersionManager.py:173 2023-02-10 15:52:10: query status of rollabck task
INFO     root:basic.py:30 2023-02-10 15:52:10: wait for 30s......
INFO     root:basic.py:30 2023-02-10 15:52:40: wait for 30s......
INFO     root:basic.py:30 2023-02-10 15:53:10: wait for 30s......
INFO     root:basic.py:30 2023-02-10 15:53:40: wait for 30s......
INFO     root:basic.py:30 2023-02-10 15:54:10: wait for 30s......
INFO     root:VersionManager.py:181 2023-02-10 15:54:41: rollabck task exec success!
INFO     root:test_version.py:319 2023-02-10 15:54:41: rollback success, wait for gnb online
INFO     root:basic.py:30 2023-02-10 15:54:41: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 15:57:41: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 15:57:41: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:57:46: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:57:51: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:57:56: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:58:01: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:58:06: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:58:11: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:58:16: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:58:21: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:58:26: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 15:58:31: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 15:58:36: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 15:58:36: gnb is online
INFO     root:test_version.py:432 2023-02-10 15:58:36:confirm if the rollback version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 15:58:36: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 15:58:37: query gnb version info from device
INFO     root:test_version.py:457 2023-02-10 15:58:37: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/ba983d882f177526071362a768a20e4a2cef8a34/D-PHY-b84629/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 15:58:37: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B090C6E80>
INFO     root:gnbManager.py:35 2023-02-10 15:58:52: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 81b6aefa6fbb61e8051f05cb5b05c25c
INFO     root:gnbManager.py:46 2023-02-10 15:58:54: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-498708312 nrsys_ver=v21.04.01-288-gba4d0d018-2d58059, nrsysRes: v21.04.01-288-gba4d0d018-2d58059
INFO     root:test_version.py:470 2023-02-10 15:58:55: version detail check success, version info[gps/nrsys]: 81b6aefa6fbb61e8051f05cb5b05c25c/v21.04.01-288-gba4d0d018-2d58059
INFO     root:test_version.py:213 2023-02-10 15:58:55run the test <2> times
INFO     root:HmsManager.py:28 2023-02-10 15:58:55: login HMS, ip: 172.16.2.220,username: root
INFO     root:HmsManager.py:30 2023-02-10 15:58:55: login HMS success!
INFO     root:HmsManager.py:46 2023-02-10 15:58:55: query gnb info
INFO     root:HmsManager.py:48 2023-02-10 15:58:55: enbId/enbName:14/Automatic-18
INFO     root:gnbManager.py:24 2023-02-10 15:58:55: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B090C69A0>
INFO     root:VersionManager.py:199 2023-02-10 15:58:55: query gnb version info from device
INFO     root:VersionManager.py:233 2023-02-10 15:58:55: query package exist in version manager or not
INFO     root:VersionManager.py:238 2023-02-10 15:58:56: the package has existed in version manager!
INFO     root:gnbManager.py:57 2023-02-10 15:58:56: open gnb log print switch.
INFO     root:gnbModel.py:91 open log print success.
INFO     root:VersionManager.py:25 2023-02-10 15:58:57: exec download task, version: BS5514_V1.20.00
INFO     root:VersionManager.py:41 2023-02-10 15:58:59: download exec success!
INFO     root:VersionManager.py:60 2023-02-10 15:58:59: query status of download task!
INFO     root:basic.py:30 2023-02-10 15:59:00: wait for 30s......
INFO     root:VersionManager.py:69 2023-02-10 15:59:30: download task exec success!
INFO     root:VersionManager.py:214 2023-02-10 15:59:30: query gnb version info from device
INFO     root:VersionManager.py:89 2023-02-10 15:59:30: exec active task!
INFO     root:VersionManager.py:102 2023-02-10 15:59:34: active exec success!
INFO     root:VersionManager.py:116 2023-02-10 15:59:34: query status of active task
INFO     root:basic.py:30 2023-02-10 15:59:34: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:00:04: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:00:34: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:01:04: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:01:34: wait for 30s......
INFO     root:VersionManager.py:124 2023-02-10 16:02:04: active task exec success!
INFO     root:test_version.py:287 2023-02-10 16:02:04: active success, gnb will auto reboot, wait for 3min......
INFO     root:basic.py:30 2023-02-10 16:02:04: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 16:05:04: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 16:05:04: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:05:10: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:05:15: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:05:20: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:05:25: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:05:30: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:05:35: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:05:40: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:05:45: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:05:50: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 16:05:55: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 16:05:55: gnb is online
INFO     root:VersionManager.py:214 2023-02-10 16:05:55: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 16:05:56: query gnb version info from device
INFO     root:test_version.py:385 2023-02-10 16:05:56:confirm if the upgrade version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 16:05:56: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 16:05:58: query gnb version info from device
INFO     root:test_version.py:409 2023-02-10 16:05:58: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/cd4d73baa4f801d9d95c3d7a306a0086da946e7f/D-PHY-c084df/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 16:05:58: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B092002B0>
INFO     root:gnbManager.py:35 2023-02-10 16:06:13: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 4bd9525882f473e5fadcf1f65639f9bc
INFO     root:gnbManager.py:46 2023-02-10 16:06:15: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-8f885f021 nrsys_ver=v21.04.01-306-g7f42f7235-8be957c, nrsysRes: v21.04.01-306-g7f42f7235-8be957c
INFO     root:test_version.py:421 2023-02-10 16:06:16: version detail check success, version info[gps/nrsys]: 4bd9525882f473e5fadcf1f65639f9bc/v21.04.01-306-g7f42f7235-8be957c
INFO     root:CellManager.py:58 2023-02-10 16:06:16: confirm if cell status is same as expect status,expect status:available
INFO     root:CellManager.py:26 2023-02-10 16:06:16: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:06:17: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:06:17: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:06:22: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:06:24: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:06:24: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:06:29: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:06:30: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:06:30: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:06:35: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:06:36: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:06:36: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:06:41: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:06:42: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:06:42: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:06:47: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:07:40: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:07:40: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:07:45: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:07:46: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:07:46: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:07:51: query cell status
INFO     root:CellManager.py:36 2023-02-10 16:07:52: cell status:available
INFO     root:CellManager.py:65 2023-02-10 16:07:52: cell status:available, expect status:available
INFO     root:basic.py:30 2023-02-10 16:07:52: wait for 60s......
INFO     root:test_version.py:137 2023-02-10 16:08:52: exec cpe business test
INFO     root:CpeManager.py:28 2023-02-10 16:08:52: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
INFO     root:CpeManager.py:48 2023-02-10 16:08:52: exec attach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=1
INFO     root:cpeModel.py:82 mattch result is:['root@OpenWrt:~# at_cmd_task', 'OK']
INFO     root:CpeManager.py:122 2023-02-10 16:08:56: confirm if pdu setup success
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:09:01: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:09:11: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:09:21: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:09:31: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:09:41: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:09:51: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:10:01: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:10:11: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:10:21: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:10:31: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:10:41: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:10:51: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:11:01: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:11:11: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:11:21: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:11:31: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:11:41: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:11:51: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:12:01: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:12:11: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:12:21: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:12:31: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:12:41: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:12:51: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:13:01: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:13:11: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:13:21: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:13:31: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:13:41: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:13:51: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:14:01: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:14:11: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:14:21: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:14:31: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:14:41: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:14:51: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:15:01: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:15:11: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:15:21: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:15:31: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:15:41: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:15:52: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:16:02: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:16:12: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:16:22: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:16:32: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:16:42: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:16:52: wait for 5s......
INFO     root:cpeModel.py:129 ip info mattch result is[]
WARNING  root:CpeManager.py:128 pdu setup failure, wait for 5s try again!
INFO     root:basic.py:30 2023-02-10 16:17:02: wait for 5s......
WARNING  root:test_version.py:147 2023-02-10 16:17:07: cpe attach failure
INFO     root:CpeManager.py:97 2023-02-10 16:17:07: exec ping command, interface: rmnet_data0
INFO     root:cpeModel.py:144 ping result mattched is:[]
INFO     root:cpeModel.py:154 packets transmitted:[]
INFO     root:cpeModel.py:163 packets received:[]
INFO     root:cpeModel.py:172 packet loss:[]
INFO     root:CpeManager.py:100 2023-02-10 16:17:32: Cpe[192.168.1.1_rmnet_data0] ping result[max/avg/min/transmitted/received/loss rate] = -1/-1/-1/-1/0/100%
INFO     root:CpeManager.py:97 2023-02-10 16:17:32: exec ping command, interface: ath0
INFO     root:cpeModel.py:144 ping result mattched is:[]
INFO     root:cpeModel.py:154 packets transmitted:[]
INFO     root:cpeModel.py:163 packets received:[]
INFO     root:cpeModel.py:172 packet loss:[]
INFO     root:CpeManager.py:100 2023-02-10 16:17:57: Cpe[192.168.1.1_ath0] ping result[max/avg/min/transmitted/received/loss rate] = -1/-1/-1/-1/0/100%
INFO     root:test_version.py:154 2023-02-10 16:17:57: start cell flow test.
INFO     root:pndManager.py:26 2023-02-10 16:17:57: login pdn server: 172.16.2.202
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_7.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:pdnModel.py:33 login pdn server success!
INFO     root:test_version.py:169 2023-02-10 16:17:57: ue traffic test
INFO     root:CpeManager.py:334 2023-02-10 16:17:57: exec DL NR TCP flow test
INFO     root:CpeManager.py:336 2023-02-10 16:17:57: add port rule
INFO     root:CpeManager.py:342 2023-02-10 16:18:08: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 16:18:08: start pdn server port listening, port: 5579
INFO     root:CpeManager.py:347 2023-02-10 16:18:09: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5579 -P 3 -R
INFO     root:basic.py:30 2023-02-10 16:18:12: wait for 15s......
INFO     root:CpeManager.py:351 2023-02-10 16:18:27: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:pndManager.py:60 2023-02-10 16:19:14: stop pdn server port listening, port: 5579
INFO     root:CpeManager.py:355 2023-02-10 16:19:16: DL TCP NR test result:
[2023-02-10 16:18:42]:0
[2023-02-10 16:18:43]:0
[2023-02-10 16:18:44]:0
[2023-02-10 16:18:45]:0
[2023-02-10 16:18:46]:0
[2023-02-10 16:18:47]:0
[2023-02-10 16:18:48]:0
[2023-02-10 16:18:49]:0
[2023-02-10 16:18:50]:0
[2023-02-10 16:18:51]:0
[2023-02-10 16:18:52]:0
[2023-02-10 16:18:53]:0
[2023-02-10 16:18:54]:0
[2023-02-10 16:18:55]:0
[2023-02-10 16:18:56]:0
[2023-02-10 16:18:57]:0
[2023-02-10 16:18:58]:0
[2023-02-10 16:18:59]:0
[2023-02-10 16:19:00]:0
[2023-02-10 16:19:01]:0
[2023-02-10 16:19:02]:0
[2023-02-10 16:19:03]:0
[2023-02-10 16:19:04]:0
[2023-02-10 16:19:05]:0
[2023-02-10 16:19:06]:0
[2023-02-10 16:19:07]:0
[2023-02-10 16:19:08]:0
[2023-02-10 16:19:09]:0
[2023-02-10 16:19:10]:0
[2023-02-10 16:19:11]:0
[2023-02-10 16:19:12]:0

INFO     root:basic.py:30 2023-02-10 16:19:16: wait for 20s......
INFO     root:CpeManager.py:298 2023-02-10 16:19:36: exec DL WIFI TCP flow test
INFO     root:CpeManager.py:300 2023-02-10 16:19:36: add port rule
INFO     root:CpeManager.py:306 2023-02-10 16:19:47: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 16:19:47: start pdn server port listening, port: 5599
INFO     root:CpeManager.py:311 2023-02-10 16:19:48: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5599 -P 3 -R
INFO     root:CpeManager.py:315 2023-02-10 16:19:51: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:basic.py:30 2023-02-10 16:20:39: wait for 20s......
INFO     root:pndManager.py:60 2023-02-10 16:20:59: stop pdn server port listening, port: 5599
INFO     root:CpeManager.py:320 2023-02-10 16:21:01: DL TCP Wifi test result:
[2023-02-10 16:20:05]:0
[2023-02-10 16:20:06]:0
[2023-02-10 16:20:07]:0
[2023-02-10 16:20:08]:0
[2023-02-10 16:20:09]:0
[2023-02-10 16:20:10]:0
[2023-02-10 16:20:11]:0
[2023-02-10 16:20:12]:0
[2023-02-10 16:20:13]:0
[2023-02-10 16:20:14]:0
[2023-02-10 16:20:15]:0
[2023-02-10 16:20:16]:0
[2023-02-10 16:20:17]:0
[2023-02-10 16:20:18]:0
[2023-02-10 16:20:19]:0
[2023-02-10 16:20:20]:0
[2023-02-10 16:20:21]:0
[2023-02-10 16:20:22]:0
[2023-02-10 16:20:23]:0
[2023-02-10 16:20:24]:0
[2023-02-10 16:20:25]:0
[2023-02-10 16:20:26]:0
[2023-02-10 16:20:27]:0
[2023-02-10 16:20:28]:0
[2023-02-10 16:20:29]:0
[2023-02-10 16:20:30]:0
[2023-02-10 16:20:31]:0
[2023-02-10 16:20:32]:0
[2023-02-10 16:20:33]:0
[2023-02-10 16:20:34]:0
[2023-02-10 16:20:35]:0

INFO     root:CpeManager.py:39 2023-02-10 16:21:01: logout cpe command model
INFO     root:test_version.py:309 2023-02-10 16:21:01: rollback gnb version:BS5514_V1.10.80P1
INFO     root:VersionManager.py:144 2023-02-10 16:21:01: exec rollabck task
INFO     root:VersionManager.py:158 2023-02-10 16:21:04: rollback exec success!
INFO     root:VersionManager.py:173 2023-02-10 16:21:04: query status of rollabck task
INFO     root:basic.py:30 2023-02-10 16:21:04: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:21:34: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:22:04: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:22:34: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:23:04: wait for 30s......
INFO     root:VersionManager.py:181 2023-02-10 16:23:34: rollabck task exec success!
INFO     root:test_version.py:319 2023-02-10 16:23:34: rollback success, wait for gnb online
INFO     root:basic.py:30 2023-02-10 16:23:34: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 16:26:34: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 16:26:34: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:26:39: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:26:44: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:26:49: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:26:54: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:26:59: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:04: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:09: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:14: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:19: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:24: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:29: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:34: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:39: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:44: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:50: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:27:55: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:00: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:05: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:10: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:15: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:20: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:25: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:30: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:35: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:40: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:45: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:50: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:28:55: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:00: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:05: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:10: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:15: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:20: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:25: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:30: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:35: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:40: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:45: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:50: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:29:55: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:00: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:05: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:11: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:16: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:21: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:26: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:31: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:36: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:41: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:46: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:51: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:30:56: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:01: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:06: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:11: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:16: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:21: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:26: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:31: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:36: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:41: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:46: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:51: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:31:56: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:32:01: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:32:06: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:32:11: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:32:16: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:32:21: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:32:26: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:32:32: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:32:37: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:32:42: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 16:32:47: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 16:32:47: gnb is online
INFO     root:test_version.py:432 2023-02-10 16:32:47:confirm if the rollback version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 16:32:47: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 16:32:47: query gnb version info from device
INFO     root:test_version.py:457 2023-02-10 16:32:48: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/ba983d882f177526071362a768a20e4a2cef8a34/D-PHY-b84629/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 16:32:48: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B0777A220>
INFO     root:gnbManager.py:35 2023-02-10 16:33:03: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 81b6aefa6fbb61e8051f05cb5b05c25c
INFO     root:gnbManager.py:46 2023-02-10 16:33:05: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-498708312 nrsys_ver=v21.04.01-288-gba4d0d018-2d58059, nrsysRes: v21.04.01-288-gba4d0d018-2d58059
INFO     root:test_version.py:470 2023-02-10 16:33:06: version detail check success, version info[gps/nrsys]: 81b6aefa6fbb61e8051f05cb5b05c25c/v21.04.01-288-gba4d0d018-2d58059
INFO     root:test_version.py:213 2023-02-10 16:33:06run the test <3> times
INFO     root:HmsManager.py:28 2023-02-10 16:33:06: login HMS, ip: 172.16.2.220,username: root
INFO     root:HmsManager.py:30 2023-02-10 16:33:06: login HMS success!
INFO     root:HmsManager.py:46 2023-02-10 16:33:06: query gnb info
INFO     root:HmsManager.py:48 2023-02-10 16:33:06: enbId/enbName:14/Automatic-18
INFO     root:gnbManager.py:24 2023-02-10 16:33:06: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B090C6340>
INFO     root:VersionManager.py:199 2023-02-10 16:33:06: query gnb version info from device
INFO     root:VersionManager.py:233 2023-02-10 16:33:06: query package exist in version manager or not
INFO     root:VersionManager.py:238 2023-02-10 16:33:06: the package has existed in version manager!
INFO     root:gnbManager.py:57 2023-02-10 16:33:06: open gnb log print switch.
INFO     root:gnbModel.py:91 open log print success.
INFO     root:VersionManager.py:25 2023-02-10 16:33:07: exec download task, version: BS5514_V1.20.00
INFO     root:VersionManager.py:41 2023-02-10 16:33:10: download exec success!
INFO     root:VersionManager.py:60 2023-02-10 16:33:10: query status of download task!
INFO     root:basic.py:30 2023-02-10 16:33:10: wait for 30s......
INFO     root:VersionManager.py:69 2023-02-10 16:33:40: download task exec success!
INFO     root:VersionManager.py:214 2023-02-10 16:33:40: query gnb version info from device
INFO     root:VersionManager.py:89 2023-02-10 16:33:43: exec active task!
INFO     root:VersionManager.py:102 2023-02-10 16:33:47: active exec success!
INFO     root:VersionManager.py:116 2023-02-10 16:33:47: query status of active task
INFO     root:basic.py:30 2023-02-10 16:33:47: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:34:17: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:34:47: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:35:17: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:35:47: wait for 30s......
INFO     root:VersionManager.py:124 2023-02-10 16:36:17: active task exec success!
INFO     root:test_version.py:287 2023-02-10 16:36:17: active success, gnb will auto reboot, wait for 3min......
INFO     root:basic.py:30 2023-02-10 16:36:17: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 16:39:17: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 16:39:17: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:39:22: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:39:27: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:39:32: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:39:37: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:39:42: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:39:48: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:39:53: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:39:58: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:40:03: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 16:40:08: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 16:40:08: gnb is online
INFO     root:VersionManager.py:214 2023-02-10 16:40:08: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 16:40:09: query gnb version info from device
INFO     root:test_version.py:385 2023-02-10 16:40:09:confirm if the upgrade version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 16:40:09: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 16:40:11: query gnb version info from device
INFO     root:test_version.py:409 2023-02-10 16:40:11: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/cd4d73baa4f801d9d95c3d7a306a0086da946e7f/D-PHY-c084df/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 16:40:11: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B0778AA90>
INFO     root:gnbManager.py:35 2023-02-10 16:40:26: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 4bd9525882f473e5fadcf1f65639f9bc
INFO     root:gnbManager.py:46 2023-02-10 16:40:28: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-8f885f021 nrsys_ver=v21.04.01-306-g7f42f7235-8be957c, nrsysRes: v21.04.01-306-g7f42f7235-8be957c
INFO     root:test_version.py:421 2023-02-10 16:40:29: version detail check success, version info[gps/nrsys]: 4bd9525882f473e5fadcf1f65639f9bc/v21.04.01-306-g7f42f7235-8be957c
INFO     root:CellManager.py:58 2023-02-10 16:40:29: confirm if cell status is same as expect status,expect status:available
INFO     root:CellManager.py:26 2023-02-10 16:40:29: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:40:31: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:40:31: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:40:36: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:40:37: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:40:37: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:40:42: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:40:44: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:40:44: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:40:49: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:40:50: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:40:50: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:40:55: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:40:56: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:40:56: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:41:01: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:41:50: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:41:50: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:41:55: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:41:56: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:41:56: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:42:01: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:42:02: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:42:02: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:42:07: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:42:08: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:42:08: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:42:13: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:42:14: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:42:14: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:42:19: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:42:20: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:42:20: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:42:25: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:42:26: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:42:26: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:42:31: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:42:31: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:42:31: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:42:36: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:42:37: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:42:37: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:42:42: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:42:43: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:42:43: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:42:48: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:42:49: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:42:49: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:42:54: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:42:55: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:42:55: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:43:00: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:43:01: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:43:01: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:43:06: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:43:07: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:43:07: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:43:12: query cell status
WARNING  root:CellManager.py:40 2023-02-10 16:43:13: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 16:43:13: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 16:43:18: query cell status
INFO     root:CellManager.py:36 2023-02-10 16:43:19: cell status:available
INFO     root:CellManager.py:65 2023-02-10 16:43:19: cell status:available, expect status:available
INFO     root:basic.py:30 2023-02-10 16:43:19: wait for 60s......
INFO     root:test_version.py:137 2023-02-10 16:44:19: exec cpe business test
INFO     root:CpeManager.py:28 2023-02-10 16:44:19: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
INFO     root:CpeManager.py:48 2023-02-10 16:44:19: exec attach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=1
INFO     root:cpeModel.py:82 mattch result is:['root@OpenWrt:~# at_cmd_task', 'OK']
INFO     root:CpeManager.py:122 2023-02-10 16:44:23: confirm if pdu setup success
INFO     root:cpeModel.py:129 ip info mattch result is['190.1.70.249', '190.3.76.136']
INFO     root:test_version.py:144 2023-02-10 16:44:28: cpe attach sussess
INFO     root:CpeManager.py:97 2023-02-10 16:44:28: exec ping command, interface: rmnet_data0
INFO     root:cpeModel.py:144 ping result mattched is:['8.980/11.638/14.621']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['20']
INFO     root:cpeModel.py:172 packet loss:['0%']
INFO     root:CpeManager.py:100 2023-02-10 16:44:53: Cpe[192.168.1.1_rmnet_data0] ping result[max/avg/min/transmitted/received/loss rate] = 14.621/11.638/8.980/20/20/0%
INFO     root:CpeManager.py:97 2023-02-10 16:44:53: exec ping command, interface: ath0
INFO     root:cpeModel.py:144 ping result mattched is:['5.123/10.697/49.938']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['20']
INFO     root:cpeModel.py:172 packet loss:['0%']
INFO     root:CpeManager.py:100 2023-02-10 16:45:18: Cpe[192.168.1.1_ath0] ping result[max/avg/min/transmitted/received/loss rate] = 49.938/10.697/5.123/20/20/0%
INFO     root:test_version.py:154 2023-02-10 16:45:18: start cell flow test.
INFO     root:pndManager.py:26 2023-02-10 16:45:18: login pdn server: 172.16.2.202
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_7.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:pdnModel.py:33 login pdn server success!
INFO     root:test_version.py:169 2023-02-10 16:45:18: ue traffic test
INFO     root:CpeManager.py:334 2023-02-10 16:45:18: exec DL NR TCP flow test
INFO     root:CpeManager.py:336 2023-02-10 16:45:18: add port rule
INFO     root:CpeManager.py:342 2023-02-10 16:45:30: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 16:45:30: start pdn server port listening, port: 5579
INFO     root:CpeManager.py:347 2023-02-10 16:45:31: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5579 -P 3 -R
INFO     root:basic.py:30 2023-02-10 16:45:36: wait for 15s......
INFO     root:CpeManager.py:351 2023-02-10 16:45:51: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:pndManager.py:60 2023-02-10 16:46:41: stop pdn server port listening, port: 5579
INFO     root:CpeManager.py:355 2023-02-10 16:46:43: DL TCP NR test result:
[2023-02-10 16:46:05]:0
[2023-02-10 16:46:06]:0
[2023-02-10 16:46:07]:59.31 M
[2023-02-10 16:46:08]:59.18 M
[2023-02-10 16:46:09]:59.31 M
[2023-02-10 16:46:10]:59.18 M
[2023-02-10 16:46:11]:59.31 M
[2023-02-10 16:46:12]:59.18 M
[2023-02-10 16:46:13]:59.31 M
[2023-02-10 16:46:14]:59.18 M
[2023-02-10 16:46:15]:59.31 M
[2023-02-10 16:46:16]:59.18 M
[2023-02-10 16:46:17]:59.31 M
[2023-02-10 16:46:18]:59.18 M
[2023-02-10 16:46:19]:59.31 M
[2023-02-10 16:46:20]:59.18 M
[2023-02-10 16:46:21]:59.31 M
[2023-02-10 16:46:22]:59.18 M
[2023-02-10 16:46:23]:59.31 M
[2023-02-10 16:46:24]:59.18 M
[2023-02-10 16:46:25]:59.31 M
[2023-02-10 16:46:26]:59.18 M
[2023-02-10 16:46:27]:59.31 M
[2023-02-10 16:46:28]:59.18 M
[2023-02-10 16:46:29]:59.31 M
[2023-02-10 16:46:30]:59.18 M
[2023-02-10 16:46:31]:59.31 M
[2023-02-10 16:46:32]:59.18 M
[2023-02-10 16:46:33]:59.31 M
[2023-02-10 16:46:34]:59.18 M
[2023-02-10 16:46:35]:59.31 M

INFO     root:basic.py:30 2023-02-10 16:46:43: wait for 20s......
INFO     root:CpeManager.py:298 2023-02-10 16:47:03: exec DL WIFI TCP flow test
INFO     root:CpeManager.py:300 2023-02-10 16:47:03: add port rule
INFO     root:CpeManager.py:306 2023-02-10 16:47:14: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 16:47:14: start pdn server port listening, port: 5599
INFO     root:CpeManager.py:311 2023-02-10 16:47:15: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5599 -P 3 -R
INFO     root:CpeManager.py:315 2023-02-10 16:47:18: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:basic.py:30 2023-02-10 16:48:05: wait for 20s......
INFO     root:pndManager.py:60 2023-02-10 16:48:25: stop pdn server port listening, port: 5599
INFO     root:CpeManager.py:320 2023-02-10 16:48:27: DL TCP Wifi test result:
[2023-02-10 16:47:32]:99.04 M
[2023-02-10 16:47:33]:0
[2023-02-10 16:47:34]:99.08 M
[2023-02-10 16:47:35]:99.08 M
[2023-02-10 16:47:36]:99.01 M
[2023-02-10 16:47:37]:99.01 M
[2023-02-10 16:47:38]:98.62 M
[2023-02-10 16:47:39]:98.62 M
[2023-02-10 16:47:40]:98.77 M
[2023-02-10 16:47:41]:98.77 M
[2023-02-10 16:47:42]:99.04 M
[2023-02-10 16:47:43]:99.04 M
[2023-02-10 16:47:44]:98.93 M
[2023-02-10 16:47:45]:98.93 M
[2023-02-10 16:47:46]:98.78 M
[2023-02-10 16:47:47]:98.78 M
[2023-02-10 16:47:48]:99.05 M
[2023-02-10 16:47:49]:99.05 M
[2023-02-10 16:47:50]:98.84 M
[2023-02-10 16:47:51]:98.84 M
[2023-02-10 16:47:52]:98.78 M
[2023-02-10 16:47:53]:98.78 M
[2023-02-10 16:47:54]:99.25 M
[2023-02-10 16:47:55]:99.25 M
[2023-02-10 16:47:56]:98.89 M
[2023-02-10 16:47:57]:98.89 M
[2023-02-10 16:47:58]:98.85 M
[2023-02-10 16:47:59]:98.85 M
[2023-02-10 16:48:00]:97.56 M
[2023-02-10 16:48:01]:97.56 M
[2023-02-10 16:48:02]:100.41 M

INFO     root:CpeManager.py:39 2023-02-10 16:48:27: logout cpe command model
INFO     root:test_version.py:309 2023-02-10 16:48:27: rollback gnb version:BS5514_V1.10.80P1
INFO     root:VersionManager.py:144 2023-02-10 16:48:27: exec rollabck task
INFO     root:VersionManager.py:158 2023-02-10 16:48:30: rollback exec success!
INFO     root:VersionManager.py:173 2023-02-10 16:48:30: query status of rollabck task
INFO     root:basic.py:30 2023-02-10 16:48:30: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:49:00: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:49:30: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:50:01: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:50:31: wait for 30s......
INFO     root:VersionManager.py:181 2023-02-10 16:51:01: rollabck task exec success!
INFO     root:test_version.py:319 2023-02-10 16:51:01: rollback success, wait for gnb online
INFO     root:basic.py:30 2023-02-10 16:51:01: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 16:54:01: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:01: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:06: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:11: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:16: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:21: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:26: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:31: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:36: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:41: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:46: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:51: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 16:54:56: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 16:55:01: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 16:55:01: gnb is online
INFO     root:test_version.py:432 2023-02-10 16:55:01:confirm if the rollback version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 16:55:01: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 16:55:02: query gnb version info from device
INFO     root:test_version.py:457 2023-02-10 16:55:02: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/ba983d882f177526071362a768a20e4a2cef8a34/D-PHY-b84629/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 16:55:02: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B0F308DC0>
INFO     root:gnbManager.py:35 2023-02-10 16:55:17: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 81b6aefa6fbb61e8051f05cb5b05c25c
INFO     root:gnbManager.py:46 2023-02-10 16:55:19: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-498708312 nrsys_ver=v21.04.01-288-gba4d0d018-2d58059, nrsysRes: v21.04.01-288-gba4d0d018-2d58059
INFO     root:test_version.py:470 2023-02-10 16:55:20: version detail check success, version info[gps/nrsys]: 81b6aefa6fbb61e8051f05cb5b05c25c/v21.04.01-288-gba4d0d018-2d58059
INFO     root:test_version.py:213 2023-02-10 16:55:20run the test <4> times
INFO     root:HmsManager.py:28 2023-02-10 16:55:20: login HMS, ip: 172.16.2.220,username: root
INFO     root:HmsManager.py:30 2023-02-10 16:55:20: login HMS success!
INFO     root:HmsManager.py:46 2023-02-10 16:55:20: query gnb info
INFO     root:HmsManager.py:48 2023-02-10 16:55:20: enbId/enbName:14/Automatic-18
INFO     root:gnbManager.py:24 2023-02-10 16:55:20: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B0F2FFC40>
INFO     root:VersionManager.py:199 2023-02-10 16:55:21: query gnb version info from device
INFO     root:VersionManager.py:233 2023-02-10 16:55:21: query package exist in version manager or not
INFO     root:VersionManager.py:238 2023-02-10 16:55:21: the package has existed in version manager!
INFO     root:gnbManager.py:57 2023-02-10 16:55:21: open gnb log print switch.
INFO     root:gnbModel.py:91 open log print success.
INFO     root:VersionManager.py:25 2023-02-10 16:55:22: exec download task, version: BS5514_V1.20.00
INFO     root:VersionManager.py:41 2023-02-10 16:55:24: download exec success!
INFO     root:VersionManager.py:60 2023-02-10 16:55:24: query status of download task!
INFO     root:basic.py:30 2023-02-10 16:55:24: wait for 30s......
INFO     root:VersionManager.py:69 2023-02-10 16:55:54: download task exec success!
INFO     root:VersionManager.py:214 2023-02-10 16:55:54: query gnb version info from device
INFO     root:VersionManager.py:89 2023-02-10 16:55:55: exec active task!
INFO     root:VersionManager.py:102 2023-02-10 16:55:59: active exec success!
INFO     root:VersionManager.py:116 2023-02-10 16:55:59: query status of active task
INFO     root:basic.py:30 2023-02-10 16:55:59: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:56:29: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:56:59: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:57:29: wait for 30s......
INFO     root:basic.py:30 2023-02-10 16:57:59: wait for 30s......
INFO     root:VersionManager.py:124 2023-02-10 16:58:29: active task exec success!
INFO     root:test_version.py:287 2023-02-10 16:58:29: active success, gnb will auto reboot, wait for 3min......
INFO     root:basic.py:30 2023-02-10 16:58:29: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 17:01:29: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 17:01:29: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:01:34: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:01:39: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:01:44: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:01:49: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:01:55: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:02:00: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:02:05: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:02:10: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:02:15: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 17:02:20: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 17:02:20: gnb is online
INFO     root:VersionManager.py:214 2023-02-10 17:02:20: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 17:02:21: query gnb version info from device
INFO     root:test_version.py:385 2023-02-10 17:02:21:confirm if the upgrade version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 17:02:21: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 17:02:23: query gnb version info from device
INFO     root:test_version.py:409 2023-02-10 17:02:23: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/cd4d73baa4f801d9d95c3d7a306a0086da946e7f/D-PHY-c084df/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 17:02:23: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B0F306100>
INFO     root:gnbManager.py:35 2023-02-10 17:02:38: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 4bd9525882f473e5fadcf1f65639f9bc
INFO     root:gnbManager.py:46 2023-02-10 17:02:40: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-8f885f021 nrsys_ver=v21.04.01-306-g7f42f7235-8be957c, nrsysRes: v21.04.01-306-g7f42f7235-8be957c
INFO     root:test_version.py:421 2023-02-10 17:02:41: version detail check success, version info[gps/nrsys]: 4bd9525882f473e5fadcf1f65639f9bc/v21.04.01-306-g7f42f7235-8be957c
INFO     root:CellManager.py:58 2023-02-10 17:02:41: confirm if cell status is same as expect status,expect status:available
INFO     root:CellManager.py:26 2023-02-10 17:02:41: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:02:42: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:02:42: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:02:47: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:02:48: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:02:48: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:02:53: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:02:54: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:02:54: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:02:59: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:00: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:00: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:03:05: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:06: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:06: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:03:11: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:11: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:11: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:03:16: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:17: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:17: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:03:22: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:23: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:23: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:03:28: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:29: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:29: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:03:34: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:35: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:35: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:03:40: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:41: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:41: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:03:46: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:47: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:47: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:03:52: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:53: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:53: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:03:58: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:03:59: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:03:59: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:04:04: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:04:04: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:04:04: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:04:09: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:04:10: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:04:10: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:04:15: query cell status
INFO     root:CellManager.py:36 2023-02-10 17:04:16: cell status:available
INFO     root:CellManager.py:65 2023-02-10 17:04:16: cell status:available, expect status:available
INFO     root:basic.py:30 2023-02-10 17:04:16: wait for 60s......
INFO     root:test_version.py:137 2023-02-10 17:05:16: exec cpe business test
INFO     root:CpeManager.py:28 2023-02-10 17:05:16: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
INFO     root:CpeManager.py:48 2023-02-10 17:05:16: exec attach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=1
INFO     root:cpeModel.py:82 mattch result is:['root@OpenWrt:~# at_cmd_task', 'OK']
INFO     root:CpeManager.py:122 2023-02-10 17:05:21: confirm if pdu setup success
INFO     root:cpeModel.py:129 ip info mattch result is['190.1.71.76', '190.3.76.206']
INFO     root:test_version.py:144 2023-02-10 17:05:26: cpe attach sussess
INFO     root:CpeManager.py:97 2023-02-10 17:05:26: exec ping command, interface: rmnet_data0
INFO     root:cpeModel.py:144 ping result mattched is:['8.855/11.834/13.541']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['20']
INFO     root:cpeModel.py:172 packet loss:['0%']
INFO     root:CpeManager.py:100 2023-02-10 17:05:51: Cpe[192.168.1.1_rmnet_data0] ping result[max/avg/min/transmitted/received/loss rate] = 13.541/11.834/8.855/20/20/0%
INFO     root:CpeManager.py:97 2023-02-10 17:05:51: exec ping command, interface: ath0
INFO     root:cpeModel.py:144 ping result mattched is:['4.707/9.150/29.723']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['20']
INFO     root:cpeModel.py:172 packet loss:['0%']
INFO     root:CpeManager.py:100 2023-02-10 17:06:16: Cpe[192.168.1.1_ath0] ping result[max/avg/min/transmitted/received/loss rate] = 29.723/9.150/4.707/20/20/0%
INFO     root:test_version.py:154 2023-02-10 17:06:16: start cell flow test.
INFO     root:pndManager.py:26 2023-02-10 17:06:16: login pdn server: 172.16.2.202
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_7.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:pdnModel.py:33 login pdn server success!
INFO     root:test_version.py:169 2023-02-10 17:06:16: ue traffic test
INFO     root:CpeManager.py:334 2023-02-10 17:06:16: exec DL NR TCP flow test
INFO     root:CpeManager.py:336 2023-02-10 17:06:16: add port rule
INFO     root:CpeManager.py:342 2023-02-10 17:06:27: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 17:06:27: start pdn server port listening, port: 5579
INFO     root:CpeManager.py:347 2023-02-10 17:06:28: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5579 -P 3 -R
INFO     root:basic.py:30 2023-02-10 17:06:31: wait for 15s......
INFO     root:CpeManager.py:351 2023-02-10 17:06:46: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:pndManager.py:60 2023-02-10 17:07:37: stop pdn server port listening, port: 5579
INFO     root:CpeManager.py:355 2023-02-10 17:07:39: DL TCP NR test result:
[2023-02-10 17:07:01]:0
[2023-02-10 17:07:02]:59.31 M
[2023-02-10 17:07:03]:59.18 M
[2023-02-10 17:07:04]:59.31 M
[2023-02-10 17:07:05]:59.18 M
[2023-02-10 17:07:06]:0
[2023-02-10 17:07:07]:118.49 M
[2023-02-10 17:07:08]:59.31 M
[2023-02-10 17:07:09]:59.18 M
[2023-02-10 17:07:10]:0
[2023-02-10 17:07:11]:59.31 M
[2023-02-10 17:07:12]:118.49 M
[2023-02-10 17:07:13]:59.18 M
[2023-02-10 17:07:14]:59.31 M
[2023-02-10 17:07:15]:0
[2023-02-10 17:07:16]:59.18 M
[2023-02-10 17:07:17]:118.49 M
[2023-02-10 17:07:18]:59.31 M
[2023-02-10 17:07:19]:59.18 M
[2023-02-10 17:07:20]:0
[2023-02-10 17:07:21]:117.75 M
[2023-02-10 17:07:22]:59.31 M
[2023-02-10 17:07:23]:58.77 M
[2023-02-10 17:07:24]:59.31 M
[2023-02-10 17:07:25]:0
[2023-02-10 17:07:26]:118.46 M
[2023-02-10 17:07:27]:59.18 M
[2023-02-10 17:07:28]:59.31 M
[2023-02-10 17:07:29]:59.18 M
[2023-02-10 17:07:30]:0
[2023-02-10 17:07:31]:118.49 M

INFO     root:basic.py:30 2023-02-10 17:07:39: wait for 20s......
INFO     root:CpeManager.py:298 2023-02-10 17:07:59: exec DL WIFI TCP flow test
INFO     root:CpeManager.py:300 2023-02-10 17:07:59: add port rule
INFO     root:CpeManager.py:306 2023-02-10 17:08:10: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 17:08:10: start pdn server port listening, port: 5599
INFO     root:CpeManager.py:311 2023-02-10 17:08:11: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5599 -P 3 -R
INFO     root:CpeManager.py:315 2023-02-10 17:08:14: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:basic.py:30 2023-02-10 17:09:01: wait for 20s......
INFO     root:pndManager.py:60 2023-02-10 17:09:21: stop pdn server port listening, port: 5599
INFO     root:CpeManager.py:320 2023-02-10 17:09:23: DL TCP Wifi test result:
[2023-02-10 17:08:28]:0
[2023-02-10 17:08:29]:0
[2023-02-10 17:08:30]:99.25 M
[2023-02-10 17:08:31]:99.25 M
[2023-02-10 17:08:32]:99.41 M
[2023-02-10 17:08:33]:99.41 M
[2023-02-10 17:08:34]:99.11 M
[2023-02-10 17:08:35]:99.11 M
[2023-02-10 17:08:36]:98.87 M
[2023-02-10 17:08:37]:98.87 M
[2023-02-10 17:08:38]:98.99 M
[2023-02-10 17:08:39]:98.99 M
[2023-02-10 17:08:40]:98.96 M
[2023-02-10 17:08:41]:98.96 M
[2023-02-10 17:08:42]:99.26 M
[2023-02-10 17:08:43]:99.26 M
[2023-02-10 17:08:44]:99.29 M
[2023-02-10 17:08:45]:99.29 M
[2023-02-10 17:08:46]:98.97 M
[2023-02-10 17:08:47]:98.97 M
[2023-02-10 17:08:48]:99.08 M
[2023-02-10 17:08:49]:99.08 M
[2023-02-10 17:08:50]:99.09 M
[2023-02-10 17:08:51]:99.09 M
[2023-02-10 17:08:52]:98.87 M
[2023-02-10 17:08:53]:98.87 M
[2023-02-10 17:08:54]:99.19 M
[2023-02-10 17:08:55]:99.19 M
[2023-02-10 17:08:56]:98.87 M
[2023-02-10 17:08:57]:98.87 M
[2023-02-10 17:08:58]:99.15 M

INFO     root:CpeManager.py:39 2023-02-10 17:09:23: logout cpe command model
INFO     root:test_version.py:309 2023-02-10 17:09:23: rollback gnb version:BS5514_V1.10.80P1
INFO     root:VersionManager.py:144 2023-02-10 17:09:23: exec rollabck task
INFO     root:VersionManager.py:158 2023-02-10 17:09:26: rollback exec success!
INFO     root:VersionManager.py:173 2023-02-10 17:09:26: query status of rollabck task
INFO     root:basic.py:30 2023-02-10 17:09:26: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:09:56: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:10:26: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:10:56: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:11:26: wait for 30s......
INFO     root:VersionManager.py:181 2023-02-10 17:11:56: rollabck task exec success!
INFO     root:test_version.py:319 2023-02-10 17:11:56: rollback success, wait for gnb online
INFO     root:basic.py:30 2023-02-10 17:11:56: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 17:14:56: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 17:14:56: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:15:01: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:15:06: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:15:11: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:15:16: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:15:21: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:15:26: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:15:31: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:15:36: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:15:41: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 17:15:46: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 17:15:46: gnb is online
INFO     root:test_version.py:432 2023-02-10 17:15:46:confirm if the rollback version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 17:15:46: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 17:15:48: query gnb version info from device
INFO     root:test_version.py:457 2023-02-10 17:15:48: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/ba983d882f177526071362a768a20e4a2cef8a34/D-PHY-b84629/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 17:15:48: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B089EB730>
INFO     root:gnbManager.py:35 2023-02-10 17:16:03: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 81b6aefa6fbb61e8051f05cb5b05c25c
INFO     root:gnbManager.py:46 2023-02-10 17:16:05: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-498708312 nrsys_ver=v21.04.01-288-gba4d0d018-2d58059, nrsysRes: v21.04.01-288-gba4d0d018-2d58059
INFO     root:test_version.py:470 2023-02-10 17:16:06: version detail check success, version info[gps/nrsys]: 81b6aefa6fbb61e8051f05cb5b05c25c/v21.04.01-288-gba4d0d018-2d58059
INFO     root:test_version.py:213 2023-02-10 17:16:06run the test <5> times
INFO     root:HmsManager.py:28 2023-02-10 17:16:06: login HMS, ip: 172.16.2.220,username: root
INFO     root:HmsManager.py:30 2023-02-10 17:16:06: login HMS success!
INFO     root:HmsManager.py:46 2023-02-10 17:16:06: query gnb info
INFO     root:HmsManager.py:48 2023-02-10 17:16:06: enbId/enbName:14/Automatic-18
INFO     root:gnbManager.py:24 2023-02-10 17:16:06: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B077837C0>
INFO     root:VersionManager.py:199 2023-02-10 17:16:06: query gnb version info from device
INFO     root:VersionManager.py:233 2023-02-10 17:16:06: query package exist in version manager or not
INFO     root:VersionManager.py:238 2023-02-10 17:16:06: the package has existed in version manager!
INFO     root:gnbManager.py:57 2023-02-10 17:16:06: open gnb log print switch.
INFO     root:gnbModel.py:91 open log print success.
INFO     root:VersionManager.py:25 2023-02-10 17:16:07: exec download task, version: BS5514_V1.20.00
INFO     root:VersionManager.py:41 2023-02-10 17:16:10: download exec success!
INFO     root:VersionManager.py:60 2023-02-10 17:16:10: query status of download task!
INFO     root:basic.py:30 2023-02-10 17:16:10: wait for 30s......
INFO     root:VersionManager.py:69 2023-02-10 17:16:40: download task exec success!
INFO     root:VersionManager.py:214 2023-02-10 17:16:40: query gnb version info from device
INFO     root:VersionManager.py:89 2023-02-10 17:16:41: exec active task!
INFO     root:VersionManager.py:102 2023-02-10 17:16:45: active exec success!
INFO     root:VersionManager.py:116 2023-02-10 17:16:45: query status of active task
INFO     root:basic.py:30 2023-02-10 17:16:45: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:17:15: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:17:45: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:18:15: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:18:45: wait for 30s......
INFO     root:VersionManager.py:124 2023-02-10 17:19:15: active task exec success!
INFO     root:test_version.py:287 2023-02-10 17:19:15: active success, gnb will auto reboot, wait for 3min......
INFO     root:basic.py:30 2023-02-10 17:19:15: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 17:22:15: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 17:22:15: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:22:20: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:22:25: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:22:30: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:22:35: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:22:40: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:22:45: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:22:50: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:22:55: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:23:00: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:23:05: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:23:10: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 17:23:15: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 17:23:15: gnb is online
INFO     root:VersionManager.py:214 2023-02-10 17:23:15: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 17:23:19: query gnb version info from device
INFO     root:test_version.py:385 2023-02-10 17:23:19:confirm if the upgrade version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 17:23:19: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 17:23:23: query gnb version info from device
INFO     root:test_version.py:409 2023-02-10 17:23:23: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/cd4d73baa4f801d9d95c3d7a306a0086da946e7f/D-PHY-c084df/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 17:23:23: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B0AA29610>
INFO     root:gnbManager.py:35 2023-02-10 17:23:38: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 4bd9525882f473e5fadcf1f65639f9bc
INFO     root:gnbManager.py:46 2023-02-10 17:23:40: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-8f885f021 nrsys_ver=v21.04.01-306-g7f42f7235-8be957c, nrsysRes: v21.04.01-306-g7f42f7235-8be957c
INFO     root:test_version.py:421 2023-02-10 17:23:41: version detail check success, version info[gps/nrsys]: 4bd9525882f473e5fadcf1f65639f9bc/v21.04.01-306-g7f42f7235-8be957c
INFO     root:CellManager.py:58 2023-02-10 17:23:41: confirm if cell status is same as expect status,expect status:available
INFO     root:CellManager.py:26 2023-02-10 17:23:41: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:23:42: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:23:42: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:23:47: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:23:48: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:23:48: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:23:53: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:23:53: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:23:53: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:23:58: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:23:59: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:23:59: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:24:04: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:24:05: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:24:05: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:24:10: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:24:11: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:24:11: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:24:16: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:24:17: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:24:17: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:24:22: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:24:23: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:24:23: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:24:28: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:24:30: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:24:30: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:24:35: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:24:36: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:24:36: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:24:41: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:24:43: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:24:43: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:24:48: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:24:49: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:24:49: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:24:54: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:24:56: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:24:56: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:25:01: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:25:02: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:25:02: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:25:07: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:25:08: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:25:08: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:25:13: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:25:14: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:25:14: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:25:19: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:25:20: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:25:20: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:25:25: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:25:25: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:25:25: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:25:30: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:25:31: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:25:31: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:25:36: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:25:37: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:25:37: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:25:42: query cell status
INFO     root:CellManager.py:36 2023-02-10 17:26:30: cell status:available
INFO     root:CellManager.py:65 2023-02-10 17:26:30: cell status:available, expect status:available
INFO     root:basic.py:30 2023-02-10 17:26:30: wait for 60s......
INFO     root:test_version.py:137 2023-02-10 17:27:30: exec cpe business test
INFO     root:CpeManager.py:28 2023-02-10 17:27:30: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
INFO     root:CpeManager.py:48 2023-02-10 17:27:30: exec attach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=1
INFO     root:cpeModel.py:82 mattch result is:['root@OpenWrt:~# at_cmd_task', 'OK']
INFO     root:CpeManager.py:122 2023-02-10 17:27:34: confirm if pdu setup success
INFO     root:cpeModel.py:129 ip info mattch result is['190.1.71.127', '190.3.76.255']
INFO     root:test_version.py:144 2023-02-10 17:27:39: cpe attach sussess
INFO     root:CpeManager.py:97 2023-02-10 17:27:39: exec ping command, interface: rmnet_data0
INFO     root:cpeModel.py:144 ping result mattched is:['9.718/12.582/14.298']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['20']
INFO     root:cpeModel.py:172 packet loss:['0%']
INFO     root:CpeManager.py:100 2023-02-10 17:28:04: Cpe[192.168.1.1_rmnet_data0] ping result[max/avg/min/transmitted/received/loss rate] = 14.298/12.582/9.718/20/20/0%
INFO     root:CpeManager.py:97 2023-02-10 17:28:04: exec ping command, interface: ath0
INFO     root:cpeModel.py:144 ping result mattched is:['4.946/10.042/58.452']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['20']
INFO     root:cpeModel.py:172 packet loss:['0%']
INFO     root:CpeManager.py:100 2023-02-10 17:28:29: Cpe[192.168.1.1_ath0] ping result[max/avg/min/transmitted/received/loss rate] = 58.452/10.042/4.946/20/20/0%
INFO     root:test_version.py:154 2023-02-10 17:28:29: start cell flow test.
INFO     root:pndManager.py:26 2023-02-10 17:28:29: login pdn server: 172.16.2.202
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_7.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:pdnModel.py:33 login pdn server success!
INFO     root:test_version.py:169 2023-02-10 17:28:29: ue traffic test
INFO     root:CpeManager.py:334 2023-02-10 17:28:29: exec DL NR TCP flow test
INFO     root:CpeManager.py:336 2023-02-10 17:28:29: add port rule
INFO     root:CpeManager.py:342 2023-02-10 17:28:40: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 17:28:40: start pdn server port listening, port: 5579
INFO     root:CpeManager.py:347 2023-02-10 17:28:41: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5579 -P 3 -R
INFO     root:basic.py:30 2023-02-10 17:28:44: wait for 15s......
INFO     root:CpeManager.py:351 2023-02-10 17:28:59: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:pndManager.py:60 2023-02-10 17:29:49: stop pdn server port listening, port: 5579
INFO     root:CpeManager.py:355 2023-02-10 17:29:51: DL TCP NR test result:
[2023-02-10 17:29:14]:0
[2023-02-10 17:29:15]:0
[2023-02-10 17:29:16]:59.31 M
[2023-02-10 17:29:17]:59.18 M
[2023-02-10 17:29:18]:59.31 M
[2023-02-10 17:29:19]:59.18 M
[2023-02-10 17:29:20]:59.31 M
[2023-02-10 17:29:21]:59.18 M
[2023-02-10 17:29:22]:59.31 M
[2023-02-10 17:29:23]:59.18 M
[2023-02-10 17:29:24]:59.31 M
[2023-02-10 17:29:25]:59.18 M
[2023-02-10 17:29:26]:59.31 M
[2023-02-10 17:29:27]:59.18 M
[2023-02-10 17:29:28]:59.26 M
[2023-02-10 17:29:29]:59.18 M
[2023-02-10 17:29:30]:59.31 M
[2023-02-10 17:29:31]:59.18 M
[2023-02-10 17:29:32]:59.31 M
[2023-02-10 17:29:33]:59.18 M
[2023-02-10 17:29:34]:59.31 M
[2023-02-10 17:29:35]:59.18 M
[2023-02-10 17:29:36]:59.31 M
[2023-02-10 17:29:37]:59.18 M
[2023-02-10 17:29:38]:59.31 M
[2023-02-10 17:29:39]:59.18 M
[2023-02-10 17:29:40]:59.31 M
[2023-02-10 17:29:41]:59.18 M
[2023-02-10 17:29:42]:59.31 M
[2023-02-10 17:29:43]:59.18 M
[2023-02-10 17:29:44]:59.31 M

INFO     root:basic.py:30 2023-02-10 17:29:51: wait for 20s......
INFO     root:CpeManager.py:298 2023-02-10 17:30:11: exec DL WIFI TCP flow test
INFO     root:CpeManager.py:300 2023-02-10 17:30:11: add port rule
INFO     root:CpeManager.py:306 2023-02-10 17:30:22: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 17:30:22: start pdn server port listening, port: 5599
INFO     root:CpeManager.py:311 2023-02-10 17:30:23: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5599 -P 3 -R
INFO     root:CpeManager.py:315 2023-02-10 17:30:26: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:basic.py:30 2023-02-10 17:31:14: wait for 20s......
INFO     root:pndManager.py:60 2023-02-10 17:31:34: stop pdn server port listening, port: 5599
INFO     root:CpeManager.py:320 2023-02-10 17:31:36: DL TCP Wifi test result:
[2023-02-10 17:30:41]:0
[2023-02-10 17:30:42]:98.85 M
[2023-02-10 17:30:43]:98.85 M
[2023-02-10 17:30:44]:98.76 M
[2023-02-10 17:30:45]:98.76 M
[2023-02-10 17:30:46]:98.59 M
[2023-02-10 17:30:47]:98.59 M
[2023-02-10 17:30:48]:98.31 M
[2023-02-10 17:30:49]:98.31 M
[2023-02-10 17:30:50]:98.31 M
[2023-02-10 17:30:51]:98.29 M
[2023-02-10 17:30:52]:98.29 M
[2023-02-10 17:30:53]:99.16 M
[2023-02-10 17:30:54]:99.16 M
[2023-02-10 17:30:55]:99.16 M
[2023-02-10 17:30:56]:99.16 M
[2023-02-10 17:30:57]:98.81 M
[2023-02-10 17:30:58]:98.81 M
[2023-02-10 17:30:59]:98.9 M
[2023-02-10 17:31:00]:98.9 M
[2023-02-10 17:31:01]:98.74 M
[2023-02-10 17:31:02]:98.74 M
[2023-02-10 17:31:03]:99.17 M
[2023-02-10 17:31:04]:99.17 M
[2023-02-10 17:31:05]:98.81 M
[2023-02-10 17:31:06]:98.81 M
[2023-02-10 17:31:07]:98.78 M
[2023-02-10 17:31:08]:98.78 M
[2023-02-10 17:31:09]:99.02 M
[2023-02-10 17:31:10]:99.02 M
[2023-02-10 17:31:11]:99.36 M

INFO     root:CpeManager.py:39 2023-02-10 17:31:36: logout cpe command model
INFO     root:test_version.py:309 2023-02-10 17:31:36: rollback gnb version:BS5514_V1.10.80P1
INFO     root:VersionManager.py:144 2023-02-10 17:31:36: exec rollabck task
INFO     root:VersionManager.py:158 2023-02-10 17:31:38: rollback exec success!
INFO     root:VersionManager.py:173 2023-02-10 17:31:38: query status of rollabck task
INFO     root:basic.py:30 2023-02-10 17:31:38: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:32:08: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:32:38: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:33:09: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:33:39: wait for 30s......
INFO     root:VersionManager.py:181 2023-02-10 17:34:09: rollabck task exec success!
INFO     root:test_version.py:319 2023-02-10 17:34:09: rollback success, wait for gnb online
INFO     root:basic.py:30 2023-02-10 17:34:09: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 17:37:09: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:09: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:14: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:19: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:24: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:29: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:34: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:39: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:44: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:49: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:54: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:37:59: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 17:38:04: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 17:38:04: gnb is online
INFO     root:test_version.py:432 2023-02-10 17:38:04:confirm if the rollback version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 17:38:04: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 17:38:05: query gnb version info from device
INFO     root:test_version.py:457 2023-02-10 17:38:05: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/ba983d882f177526071362a768a20e4a2cef8a34/D-PHY-b84629/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 17:38:05: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B118BC280>
INFO     root:gnbManager.py:35 2023-02-10 17:38:20: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 81b6aefa6fbb61e8051f05cb5b05c25c
INFO     root:gnbManager.py:46 2023-02-10 17:38:22: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-498708312 nrsys_ver=v21.04.01-288-gba4d0d018-2d58059, nrsysRes: v21.04.01-288-gba4d0d018-2d58059
INFO     root:test_version.py:470 2023-02-10 17:38:24: version detail check success, version info[gps/nrsys]: 81b6aefa6fbb61e8051f05cb5b05c25c/v21.04.01-288-gba4d0d018-2d58059
INFO     root:test_version.py:213 2023-02-10 17:38:24run the test <6> times
INFO     root:HmsManager.py:28 2023-02-10 17:38:24: login HMS, ip: 172.16.2.220,username: root
INFO     root:HmsManager.py:30 2023-02-10 17:38:24: login HMS success!
INFO     root:HmsManager.py:46 2023-02-10 17:38:24: query gnb info
INFO     root:HmsManager.py:48 2023-02-10 17:38:24: enbId/enbName:14/Automatic-18
INFO     root:gnbManager.py:24 2023-02-10 17:38:24: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B118E5820>
INFO     root:VersionManager.py:199 2023-02-10 17:38:24: query gnb version info from device
INFO     root:VersionManager.py:233 2023-02-10 17:38:24: query package exist in version manager or not
INFO     root:VersionManager.py:238 2023-02-10 17:38:24: the package has existed in version manager!
INFO     root:gnbManager.py:57 2023-02-10 17:38:24: open gnb log print switch.
INFO     root:gnbModel.py:91 open log print success.
INFO     root:VersionManager.py:25 2023-02-10 17:38:25: exec download task, version: BS5514_V1.20.00
INFO     root:VersionManager.py:41 2023-02-10 17:38:28: download exec success!
INFO     root:VersionManager.py:60 2023-02-10 17:38:28: query status of download task!
INFO     root:basic.py:30 2023-02-10 17:38:28: wait for 30s......
INFO     root:VersionManager.py:69 2023-02-10 17:38:58: download task exec success!
INFO     root:VersionManager.py:214 2023-02-10 17:38:58: query gnb version info from device
INFO     root:VersionManager.py:89 2023-02-10 17:38:59: exec active task!
INFO     root:VersionManager.py:102 2023-02-10 17:39:03: active exec success!
INFO     root:VersionManager.py:116 2023-02-10 17:39:03: query status of active task
INFO     root:basic.py:30 2023-02-10 17:39:03: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:39:33: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:40:03: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:40:33: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:41:03: wait for 30s......
INFO     root:VersionManager.py:124 2023-02-10 17:41:33: active task exec success!
INFO     root:test_version.py:287 2023-02-10 17:41:33: active success, gnb will auto reboot, wait for 3min......
INFO     root:basic.py:30 2023-02-10 17:41:33: wait for 180s......
INFO     root:DeviceManager.py:21 2023-02-10 17:44:33: confirm if gnb is online
WARNING  root:deviceManagerService.py:40 2023-02-10 17:44:33: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:44:38: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:44:43: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:44:48: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:44:53: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:44:58: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:45:03: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:45:08: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:45:13: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:45:18: device is offline, wait 5s try again!
WARNING  root:deviceManagerService.py:40 2023-02-10 17:45:23: device is offline, wait 5s try again!
INFO     root:deviceManagerService.py:36 2023-02-10 17:45:28: device is online!
INFO     root:DeviceManager.py:24 2023-02-10 17:45:28: gnb is online
INFO     root:VersionManager.py:214 2023-02-10 17:45:28: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 17:45:29: query gnb version info from device
INFO     root:test_version.py:385 2023-02-10 17:45:29:confirm if the upgrade version detail is correct.
INFO     root:VersionManager.py:214 2023-02-10 17:45:29: query gnb version info from device
INFO     root:VersionManager.py:199 2023-02-10 17:45:31: query gnb version info from device
INFO     root:test_version.py:409 2023-02-10 17:45:31: version detail check success, version info[wifi/fpgapl/fpgaps/dphy/cphy/cpld]: W6AP-1000_20220929_C00_V07/22040903/cd4d73baa4f801d9d95c3d7a306a0086da946e7f/D-PHY-c084df/C-PHY-V1.10.80/229231
INFO     root:gnbManager.py:24 2023-02-10 17:45:31: login gnb by ssh.
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_8.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:gnbService.py:28 ssh login gnb success, gnb: <BasicModel.gnb.gnbModel.gnbModel object at 0x0000016B1182C580>
INFO     root:gnbManager.py:35 2023-02-10 17:45:46: query gps md5 value.
INFO     root:gnbService.py:74 md5sum: 4bd9525882f473e5fadcf1f65639f9bc
INFO     root:gnbManager.py:46 2023-02-10 17:45:48: query nrsys/uboot version.
INFO     root:gnbService.py:82 ubootRes: 2019.10v21.04.01-8f885f021 nrsys_ver=v21.04.01-306-g7f42f7235-8be957c, nrsysRes: v21.04.01-306-g7f42f7235-8be957c
INFO     root:test_version.py:421 2023-02-10 17:45:49: version detail check success, version info[gps/nrsys]: 4bd9525882f473e5fadcf1f65639f9bc/v21.04.01-306-g7f42f7235-8be957c
INFO     root:CellManager.py:58 2023-02-10 17:45:49: confirm if cell status is same as expect status,expect status:available
INFO     root:CellManager.py:26 2023-02-10 17:45:49: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:45:50: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:45:50: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:45:55: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:45:56: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:45:56: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:46:01: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:46:02: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:46:02: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:46:07: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:46:08: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:46:08: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:46:13: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:46:14: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:46:14: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:46:19: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:46:20: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:46:20: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:46:25: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:46:26: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:46:26: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:46:31: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:46:32: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:46:32: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:46:37: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:46:38: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:46:38: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:46:43: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:46:44: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:46:44: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:46:49: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:46:50: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:46:50: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:46:55: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:46:56: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:46:56: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:47:01: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:47:02: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:47:02: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:47:07: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:47:08: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:47:08: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:47:13: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:47:13: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:47:13: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:47:18: query cell status
WARNING  root:CellManager.py:40 2023-02-10 17:47:19: cell status:unavailable
INFO     root:basic.py:30 2023-02-10 17:47:19: wait for 5s......
INFO     root:CellManager.py:26 2023-02-10 17:47:24: query cell status
INFO     root:CellManager.py:36 2023-02-10 17:47:25: cell status:available
INFO     root:CellManager.py:65 2023-02-10 17:47:25: cell status:available, expect status:available
INFO     root:basic.py:30 2023-02-10 17:47:25: wait for 60s......
INFO     root:test_version.py:137 2023-02-10 17:48:25: exec cpe business test
INFO     root:CpeManager.py:28 2023-02-10 17:48:25: login cpe command model
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client dropbear)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:cpeModel.py:35 login cpe success!
INFO     root:CpeManager.py:48 2023-02-10 17:48:25: exec attach command
INFO     root:cpeModel.py:58 AT Command is:at+cfun=1
INFO     root:cpeModel.py:82 mattch result is:['root@OpenWrt:~# at_cmd_task', 'OK']
INFO     root:CpeManager.py:122 2023-02-10 17:48:30: confirm if pdu setup success
INFO     root:cpeModel.py:129 ip info mattch result is['190.1.71.206', '190.3.77.74']
INFO     root:test_version.py:144 2023-02-10 17:48:35: cpe attach sussess
INFO     root:CpeManager.py:97 2023-02-10 17:48:35: exec ping command, interface: rmnet_data0
INFO     root:cpeModel.py:144 ping result mattched is:['8.632/11.278/13.903']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['20']
INFO     root:cpeModel.py:172 packet loss:['0%']
INFO     root:CpeManager.py:100 2023-02-10 17:49:00: Cpe[192.168.1.1_rmnet_data0] ping result[max/avg/min/transmitted/received/loss rate] = 13.903/11.278/8.632/20/20/0%
INFO     root:CpeManager.py:97 2023-02-10 17:49:00: exec ping command, interface: ath0
INFO     root:cpeModel.py:144 ping result mattched is:['4.789/10.181/57.232']
INFO     root:cpeModel.py:154 packets transmitted:['20']
INFO     root:cpeModel.py:163 packets received:['20']
INFO     root:cpeModel.py:172 packet loss:['0%']
INFO     root:CpeManager.py:100 2023-02-10 17:49:25: Cpe[192.168.1.1_ath0] ping result[max/avg/min/transmitted/received/loss rate] = 57.232/10.181/4.789/20/20/0%
INFO     root:test_version.py:154 2023-02-10 17:49:25: start cell flow test.
INFO     root:pndManager.py:26 2023-02-10 17:49:25: login pdn server: 172.16.2.202
INFO     paramiko.transport:transport.py:1874 Connected (version 2.0, client OpenSSH_7.4)
INFO     paramiko.transport:transport.py:1874 Authentication (password) successful!
INFO     root:pdnModel.py:33 login pdn server success!
INFO     root:test_version.py:169 2023-02-10 17:49:25: ue traffic test
INFO     root:CpeManager.py:334 2023-02-10 17:49:25: exec DL NR TCP flow test
INFO     root:CpeManager.py:336 2023-02-10 17:49:25: add port rule
INFO     root:CpeManager.py:342 2023-02-10 17:49:36: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 17:49:36: start pdn server port listening, port: 5579
INFO     root:CpeManager.py:347 2023-02-10 17:49:37: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5579 -P 3 -R
INFO     root:basic.py:30 2023-02-10 17:49:40: wait for 15s......
INFO     root:CpeManager.py:351 2023-02-10 17:49:55: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:pndManager.py:60 2023-02-10 17:50:45: stop pdn server port listening, port: 5579
INFO     root:CpeManager.py:355 2023-02-10 17:50:47: DL TCP NR test result:
[2023-02-10 17:50:10]:0
[2023-02-10 17:50:11]:59.22 M
[2023-02-10 17:50:12]:59.26 M
[2023-02-10 17:50:13]:0
[2023-02-10 17:50:14]:59.22 M
[2023-02-10 17:50:15]:118.49 M
[2023-02-10 17:50:16]:59.26 M
[2023-02-10 17:50:17]:59.22 M
[2023-02-10 17:50:18]:0
[2023-02-10 17:50:19]:118.49 M
[2023-02-10 17:50:20]:59.26 M
[2023-02-10 17:50:21]:59.22 M
[2023-02-10 17:50:22]:59.26 M
[2023-02-10 17:50:23]:0
[2023-02-10 17:50:24]:118.49 M
[2023-02-10 17:50:25]:59.22 M
[2023-02-10 17:50:26]:59.26 M
[2023-02-10 17:50:27]:0
[2023-02-10 17:50:28]:59.22 M
[2023-02-10 17:50:29]:118.49 M
[2023-02-10 17:50:30]:59.26 M
[2023-02-10 17:50:31]:59.22 M
[2023-02-10 17:50:32]:0
[2023-02-10 17:50:33]:59.26 M
[2023-02-10 17:50:34]:118.49 M
[2023-02-10 17:50:35]:59.22 M
[2023-02-10 17:50:36]:59.26 M
[2023-02-10 17:50:37]:0
[2023-02-10 17:50:38]:118.49 M
[2023-02-10 17:50:39]:59.22 M
[2023-02-10 17:50:40]:59.26 M

INFO     root:basic.py:30 2023-02-10 17:50:47: wait for 20s......
INFO     root:CpeManager.py:298 2023-02-10 17:51:07: exec DL WIFI TCP flow test
INFO     root:CpeManager.py:300 2023-02-10 17:51:07: add port rule
INFO     root:CpeManager.py:306 2023-02-10 17:51:18: binding port rule success!
INFO     root:pndManager.py:48 2023-02-10 17:51:18: start pdn server port listening, port: 5599
INFO     root:CpeManager.py:311 2023-02-10 17:51:19: exec iperf command
INFO     root:cpeModel.py:208 iperf command[tcp-dl]: D:\iperf-3.1.3-win64\iperf3 -c 193.168.9.223 -b 500m -i 1 -t 60 -l 1300 -p 5599 -P 3 -R
INFO     root:CpeManager.py:315 2023-02-10 17:51:22: start scrap process, analyze data
INFO     root:loadFileAndAnalyzeData.py:336 begin capture data package, capture time: 30s......
INFO     root:basic.py:30 2023-02-10 17:52:10: wait for 20s......
INFO     root:pndManager.py:60 2023-02-10 17:52:30: stop pdn server port listening, port: 5599
INFO     root:CpeManager.py:320 2023-02-10 17:52:32: DL TCP Wifi test result:
[2023-02-10 17:51:37]:0
[2023-02-10 17:51:38]:98.68 M
[2023-02-10 17:51:39]:98.68 M
[2023-02-10 17:51:40]:98.23 M
[2023-02-10 17:51:41]:98.23 M
[2023-02-10 17:51:42]:98.53 M
[2023-02-10 17:51:43]:98.53 M
[2023-02-10 17:51:44]:98.37 M
[2023-02-10 17:51:45]:98.37 M
[2023-02-10 17:51:46]:98.41 M
[2023-02-10 17:51:47]:98.41 M
[2023-02-10 17:51:48]:98.68 M
[2023-02-10 17:51:49]:98.68 M
[2023-02-10 17:51:50]:99.61 M
[2023-02-10 17:51:51]:99.61 M
[2023-02-10 17:51:52]:99.24 M
[2023-02-10 17:51:53]:99.24 M
[2023-02-10 17:51:54]:98.91 M
[2023-02-10 17:51:55]:98.91 M
[2023-02-10 17:51:56]:98.79 M
[2023-02-10 17:51:57]:98.79 M
[2023-02-10 17:51:58]:98.7 M
[2023-02-10 17:51:59]:98.7 M
[2023-02-10 17:52:00]:98.85 M
[2023-02-10 17:52:01]:98.85 M
[2023-02-10 17:52:02]:98.34 M
[2023-02-10 17:52:03]:98.34 M
[2023-02-10 17:52:04]:99.21 M
[2023-02-10 17:52:05]:99.21 M
[2023-02-10 17:52:06]:98.9 M
[2023-02-10 17:52:07]:98.9 M

INFO     root:CpeManager.py:39 2023-02-10 17:52:32: logout cpe command model
INFO     root:test_version.py:309 2023-02-10 17:52:32: rollback gnb version:BS5514_V1.10.80P1
INFO     root:VersionManager.py:144 2023-02-10 17:52:32: exec rollabck task
INFO     root:VersionManager.py:158 2023-02-10 17:52:45: rollback exec success!
INFO     root:VersionManager.py:173 2023-02-10 17:52:45: query status of rollabck task
INFO     root:basic.py:30 2023-02-10 17:52:45: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:53:15: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:53:45: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:54:15: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:54:45: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:55:15: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:55:45: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:56:15: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:56:45: wait for 30s......
INFO     root:basic.py:30 2023-02-10 17:57:15: wait for 30s......
INFO     root:VersionManager.py:189 2023-02-10 17:57:45: rollback task is execing!